#COMMON CONFIG
spring:
  main:
    banner-mode: off

# DATABASE CONFIG
  datasource:
    url: jdbc:postgresql://localhost:5432/token_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/token_db
    user: postgres
    password: admin
    default-schema: public


# LOGGING CONFIG
logging:
  level:
    org:
      springframework:
        security: DEBUG


# SERVER CONFIG
server:
  port: 8081

# GRPC CONFIG
grpc:
  port: 6061
  security:
    auth:
      enabled: true
  enable-reflection: true
  client:
    user-service:
      address: localhost
      port: 6060

# INSTANCE CONFIG
instance:
  key: "authentication-service"
  id: 1

# JWT CONFIG
jwt:
  key: 702ECF979164043FF68BD276F95409E6DC10167123D967F0AB78FA8DBCA02062
  access-expiration: 86400000
  refresh-expiration: 604800000

